### ISSUE TITLE
Incompatible with ESGST "Game Tags" feature

### ISSUE THREAD

**Issue by Moony1986** [Laurvin/SteamGifts-GA-Table-Creator#1]
The giveaways are not extracted if the game has an user defined tag (ESGST option 7.3)

![ESGST-Tags](https://user-images.githubusercontent.com/37914971/61657525-6daa7a80-acc3-11e9-88a8-212bb31539bf.jpg)

**Comment by Laurvin** [comment]
Fixed it. :)

Turns out ESGST changed stuff and put things outside the <span>.
